version: '3.8'
services:
  mysql-62tek:
    build:
      context: ./backend/mysql
      dockerfile: Dockerfile
    # image: mariadb
    restart: always
    stdin_open: true # docker run -i
    tty: true
    ports:
      - '3306:3306'
    volumes:
      - mysql-62test:/var/lib/mysql
      # - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: interview
  backend-62tek:
    build: ./backend
    ports:
      - '3001:3000'
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mysql-62tek
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
volumes:
  mysql-62test:
